export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REQUEST_FETCH_LOGIN = 'REQUEST_FETCH_LOGIN';
export const ERROR = 'ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const REQUEST_FETCH_REGISTER = 'REQUEST_FETCH_REGISTER';
export const PROFILE_INIT = 'PROFILE_INIT';
export default {
    LOGIN,
    LOGOUT,
    REQUEST_FETCH_LOGIN,
    ERROR,
    CLEAR_ERROR,
    REQUEST_FETCH_REGISTER,
    PROFILE_INIT
  };